# yaml-language-server: $schema=https://raw.githubusercontent.com/DavidAnson/markdownlint/refs/heads/main/schema/markdownlint-config-schema-strict.json
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Enable all rules by default
default: true

# Path to config file to extend
extends: null

# Rules
no-alt-text: false
no-inline-html: false
single-h1:
  front_matter_title: ^\s*title\s*[:=]
line-length: false
no-duplicate-heading:
  siblings_only: true
no-trailing-spaces:
  br_spaces: 2
  list_item_empty_lines: false
  strict: true
no-hard-tabs:
  code_blocks: true
  spaces_per_tab: 2
no-emphasis-as-heading: false
no-blanks-blockquote: false
descriptive-link-text: false
ul-indent:
  indent: 2
  start_indented: false
ul-style:
  style: dash
ol-prefix:
  style: one_or_ordered
table-pipe-style:
  style: leading_and_trailing
heading-style:
  style: atx
code-block-style:
  style: fenced
code-fence-style:
  style: backtick
emphasis-style:
  style: asterisk
strong-style:
  style: asterisk
